### ISSUE TITLE
 Great project. But how to generate terrain dem pmtiles files?

### ISSUE THREAD

**Issue by anders86755** [jebowe3/adirondack-high-peaks-1899#1]
I know how to generate vector pmtiles files, but I don’t know how to generate pmtiles for terrain dem, and I haven’t found a solution on the Internet.

**Comment by jebowe3** [comment]
I have some explanation of this process here: [https://github.com/jebowe3/Mt-Everest-NGM-1988-3D](https://github.com/jebowe3/Mt-Everest-NGM-1988-3D). 

First, you will want to create an RGB color scale range from the lowest elevation to the highest elevation in your data and save this in a txt file. In the example of Everest, using 3590 - 8890 meters, I assigned the RGB range (68,1,84 - 253,231,37) as follows:

3590 68 1 84
8890 253 231 37

Next, you will want to map your DEM to this color range with the following code, which I ran in Mac Terminal using gdaldem:

gdaldem color-relief input_dem.tif color_relief.txt output_rgb.tif

Then, using rio in Terminal, convert the output rgb file to mbtiles as follows (feel free to adjust the output options as needed):

rio mbtiles output_rgb.tif output_rgb.mbtiles --format PNG --zoom-levels 0..14 --tile-size 256 --resampling bilinear

Lastly, convert the output mbtiles to pmtiles in Terminal:

pmtiles convert output_rgb.mbtiles output_rgb.pmtiles

Using this process, you should get what you need.

**Comment by anders86755** [comment]
Thank you so much! I understand how to do it.
